### ISSUE TITLE
Chinese translate

### ISSUE THREAD

**Issue by Cha-Shao** [PluginBugs/Issues-CosmeticsCore#1]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

add Chinese translate

### Is your feature request related to a problem?

1

### Describe alternatives you've considered

1

### Additional context

```yaml
current-color: "当前颜色: {value}"
cosmetic-icon-lore-equip: "左键装备"
cosmetic-icon-lore-unequip: "左键卸下"
cosmetic-icon-lore-customize: "右键染色"
```
