### ISSUE TITLE
Cosmetics Group/Variant option

### ISSUE THREAD

**Issue by Andre601** [PluginBugs/Issues-CosmeticsCore#104]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Andre_601#0601

### Describe the solution you'd like

An option to group cosmetics together. When the player would then select a cosmetic that is grouped, could they pick from all the available variants.

It would allow to keep items grouped together while also keeping the GUI small in size.

To give a more concrete example:
Imagine having a "Fox cosmetics" set that adds fox ears and tails for both normal (red) and snow fox.
Now, you could group them together like this (Assuming ItemsAdder was used too):
```yaml
cosmetics:
  fox_ears:
    display_name: "Fox Ears"
    type: HAT
    model:
      gui: foxcosmetics:fox_ears
      normal: foxcosmetics:fox_ears
    dye:
      enabled: false
  snow_fox_ears:
    display_name: "Snow Fox Ears"
    type: HAT
    model:
      gui: foxcosmetics:snow_fox_ears
      normal: foxcosmetics:snow_fox_ears
    dye:
      enabled: false
  fox_tail:
    display_name: "Fox Tail"
    type: BODY_ITEM
    model:
      gui: foxcosmetics:fox_tail
      normal: foxcosmetics:fox_tail
    dye:
      enabled: false
  snow_fox_tail:
    display_name: "Snow Fox Tail"
    type: BODY_ITEM
    model:
      gui: foxcosmetics:snow_fox_tail
      normal: foxcosmetics:snow_fox_tail
    dye:
      enabled: false

# Defines groupings of cosmetics.
groups:
  fox-ears:
    display-item: foxcosmetics:fox_ears
    items:
    - fox_ears
    - snow_fox_ears
  fox-tails:
    display-item: foxcosmetics:fox_tail
    items:
    - fox_tail
    - snow_fox_tail
```
This would now display a single item for fox ears and fox tails respectively. Clicking on one would display a new GUI where you can select the actual variant you want to wear.

### Is your feature request related to a problem?

Cosmetics are ordered by alphabet as far as I can tell, which can cause some strange display where cosmetics of the same pack are separated from each other. Not to mention could some cosmetics look similar to each other, making it more confusing to find the right one.

### Describe alternatives you've considered

At most using a different name for the cosmetic to have them grouped closer together (i.e. prefix them with the namespace) and perhaps using a separate item for the GUI to avoid confusion.
