### ISSUE TITLE
Option to add invisible buttons into the selection GUI

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-CosmeticsCore#115]
Add an option to add invisible items (for example PAPER) into the GUI to allow bedrock edition players to click on empty slots.

**Comment by LoneDev6** [comment]
This is useful only for some expert users that need to do some crazy stuff.
Do not enable it if you don't know what you are doing.

```yml
      add_item_in_blank_slots:
        enabled: true
        type: PAPER
        custom_model_data: 1337666
```
