### ISSUE TITLE
Add `max_amount_reached_owned` and `max_amount_reached_not_owned` colors

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-CosmeticsCore#145]
More info: https://forum.devs.beer/d/631-cc-disabled-color-slots-in-config/2

> Is there a way to disable "max_amount_reached" color slot ?
The thing is, if you equip a cosmetic that you can set a value for the max equipable, that color overrides the "not_owned" color.
Which means that when you click to try on a cosmetic, in the interface you no longer know at all what you own or not.

I can fix it by providing some configuration for 2 new colors:
`max_amount_reached_owned`
`max_amount_reached_not_owned`
```yml
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached_owned: 24, 29, 43
        max_amount_reached_not_owned: 64, 48, 17
```

I opened a Github suggestion for you since the forum is not good to keep track of requests:
