### ISSUE TITLE
max_equippable:     isnt working

### ISSUE THREAD

**Issue by MelonCraftDE** [PluginBugs/Issues-CosmeticsCore#15]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

Bornyyy#9630

### What happened?

tried to change the value to 3, so i can wear a hat, sunglasses and a cigar :D suddenly only 1 item is allowed, no matter what i try.
but even after a restart, the plugin only allows to set up 1 hat item 
also i can wear 4 backpacks, even if the config says only 2 or 3 allowed.

i'm sure it was working in the first release.

### Steps to reproduce the issue

1. change the value of max_equippable:  hat:
2. try to wear more than 1 hat. 

### Server version

> version
[15:56:05 INFO]: Checking version, please wait...
[15:56:05 INFO]: This server is running Paper version git-Paper-153 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 63cb747)

### CosmeticsCore Version

> version CosmeticsCore
[15:56:17 INFO]: CosmeticsCore version 1.0.1-beta2

### ProtocolLib Version

> version ProtocolLib
[15:56:29 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-b600
[15:56:29 INFO]: Provides read/write access to the Minecraft protocol.
[15:56:29 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

> version lonelibs
[15:56:42 INFO]: LoneLibs version 1.0.21
[15:56:42 INFO]: Collection of libs used by my plugins
[15:56:42 INFO]: Authors: LoneDev and others

### Error (optional)

```shell
no errors
```

### CosmeticsCore config.yml

```shell
lang: de
cosmetics:
  max_equippable:
    hat: 3
    body: 3
    balloon: 1
wardrobe_room:
  camera:
    rotation:
      enabled: true
    zoom:
      enabled: true
      min: 2
    fade_effect: true
    location:
      world: Towny
      x: -1040.803770469599
      y: 77.62000000476837
      z: 4318.342006951915
      yaw: 89.649734
      pitch: 8.850035
  mannequin:
    location:
      world: Towny
      x: -1044.6981137014982
      y: 76.0
      z: 4318.4844724382965
      yaw: -91.70101
      pitch: 3.7500453
  teleport_area:
    enter:
      world: Towny
      pos1:
        x: -1034.0
        y: 78.0
        z: 4320.0
      pos2:
        x: -1034.0
        y: 76.0
        z: 4324.0
    exit_location:
      world: Towny
      x: -1042.407890943353
      y: 76.0
      z: 4310.120570265795
      yaw: 89.34985
      pitch: 14.400021
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
save:
  # Use only one at a time
  file:
    enabled: true
  mysql:
    enabled: false
    url: jdbc:mysql://my_url_database_69.com:3306/database_name
    username: username
    password: password
    table: cosmeticscore_saved
debug: false
extract_default_assets: true
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://www.youtube.com/watch?v=s0_ZDzNHbyM

**Comment by MelonCraftDE** [comment]
```
cosmetics:
  mining_helmet:
    display_name: "Mining Helmet"
    type: HAT
    model:
      gui: iawearables:mining_helmet
      normal: iawearables:mining_helmet
    dye:
      enabled: false
      
  cool_sunglasses:
    display_name: "Coole Sonnenbrille"
    type: HAT
    model:
      gui: iawearables:cool_sunglasses
      normal: iawearables:cool_sunglasses
    dye:
      enabled: false
      
  glasses:
    display_name: "Brille"
    type: HAT
    model:
      gui: iawearables:glasses
      normal: iawearables:glasses
    dye:
      enabled: false
      
  black_cat_tail:
    display_name: "Schwarzer Katzenschwanz"
    type: BODY_ITEM
    model:
      gui: iawearables:black_cat_tail
      normal: iawearables:black_cat_tail
    dye:
      enabled: false
      
  all_black_cat_tail:
    display_name: "Schwarzer Katzenschwanz 2"
    type: BODY_ITEM
    model:
      gui: iawearables:all_black_cat_tail
      normal: iawearables:all_black_cat_tail
    dye:
      enabled: false
      
  white_cat_tail:
    display_name: "Weißer Katzenschwanz"
    type: BODY_ITEM
    model:
      gui: iawearables:white_cat_tail
      normal: iawearables:white_cat_tail
    dye:
      enabled: false
      
  cat_ears:
    display_name: "Katzenohren"
    type: HAT
    model:
      gui: iawearables:cat_ears
      normal: iawearables:cat_ears
    dye:
      enabled: false
      
  cigar:
    display_name: "Zigarre"
    type: HAT
    model:
      gui: iawearables:cigar
      normal: iawearables:cigar
    dye:
      enabled: false
      
  ruby_pickaxe_hat:
    display_name: "Spitzhacken Hut"
    type: HAT
    model:
      gui: iawearables:ruby_pickaxe_hat
      normal: iawearables:ruby_pickaxe_hat
    dye:
      enabled: false
      
  black_backpack:
    display_name: "Schwarzer Rucksack"
    type: BODY_ITEM
    model:
      gui: iawearables:black_backpack
      normal: iawearables:black_backpack
    dye:
      enabled: false
      
  brown_backpack:
    display_name: "Brauner Rucksack"
    type: BODY_ITEM
    model:
      gui: iawearables:brown_backpack
      normal: iawearables:brown_backpack
    dye:
      enabled: false
      
  bones_backpack:
    display_name: "Knochen Rucksack"
    type: BODY_ITEM
    model:
      gui: iafestivities:bones_backpack
      normal: iafestivities:bones_backpack
    dye:
      enabled: false
      
  jack_o_lantern_backpack:
    display_name: "Kürbis Rucksack"
    type: BODY_ITEM
    model:
      gui: iafestivities:jack_o_lantern_backpack
      normal: iafestivities:jack_o_lantern_backpack
    dye:
      enabled: false
      
  dark_jack_o_lantern_backpack:
    display_name: "Dunkler Kürbis Rucksack"
    type: BODY_ITEM
    model:
      gui: iafestivities:dark_jack_o_lantern_backpack
      normal: iafestivities:dark_jack_o_lantern_backpack
    dye:
      enabled: false
      
  spider_backpack:
    display_name: "Spinnenrucksack"
    type: BODY_ITEM
    model:
      gui: iafestivities:spider_backpack
      normal: iafestivities:spider_backpack
    dye:
      enabled: false
      
  cave_spider_backpack:
    display_name: "Höhlenspinnenrucksack"
    type: BODY_ITEM
    model:
      gui: iafestivities:cave_spider_backpack
      normal: iafestivities:cave_spider_backpack
    dye:
      enabled: false
```
