### ISSUE TITLE
Prohibit command entry

### ISSUE THREAD

**Issue by Lerphie** [PluginBugs/Issues-CosmeticsCore#155]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Coder#6926

### Describe the solution you'd like

I need to add a function to the config that will prevent any commands from being entered when entering the closet. Why would I do that? My emotion plugin is breaking because players can play them directly in the closet. 

### Is your feature request related to a problem?

.

### Describe alternatives you've considered

.

**Comment by LoneDev6** [comment]
New settings will be implemented
```yml
  commands:
    blacklist:
      enabled: false
      list:
      - home
      - sethome
    whitelist:
      enabled: true
      list:
        - msg
        - tell
        - r
        - reply
        - help
```
