### ISSUE TITLE
Ability to force ordering of items in wardrobe GUI

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-CosmeticsCore#158]
Example configuration:
```yml
wardrobe:
  cosmetics_order:
    - hat1
    - hat2
    - hat3
    - hat_special_1
    - hat_special_2
    - hat_special_3
    - hat_special_4
cosmetics:
  hat_2_1:
    enabled: true
    display_name: "2 - test custom hat 1"
    type: HAT
    model:
      gui: potion:400005
      normal: potion:400005
    dye:
      enabled: false
##### ........... all cosmetics
```
