### ISSUE TITLE
Red Balloons via ModelEngine 4

### ISSUE THREAD

**Issue by BendersRepublic** [PluginBugs/Issues-CosmeticsCore#174]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

PapaWulf#0001

### What happened?

I installed ModelEngine v4. Using CosmeticsCore 1.2.3

But for some reason, my balloons are red when they come from cosmeticscore. I tried to enable dye, then set it to white, and nothing happened. Also note that the dyes are originally all disabled on the cosmetics config.

using /meg disguise, my balloons are colored properly

### Steps to reproduce the issue

/wardrobe
pick a balloon
see it be red while using modelengine4

### Server version

Current: git-Purpur-2044 (MC: 1.20.1)*

### CosmeticsCore Version

CosmeticsCore version 1.2.3

### ProtocolLib Version

ProtocolLib version 5.1.1-SNAPSHOT-668

### LoneLibs Version

LoneLibs version 1.0.27

### FULL server log

https://mclo.gs/jG0ILEZ

### CosmeticsCore config.yml

```shell
lang: en
extract_default_assets: true
cosmetics:
  max_equippable:
    body: 3
    balloon: 2
wardrobe_room:
  camera:
    hide_actionbar_texts: true
    rotation:
      enabled: true
    zoom:
      enabled: true
      min: 2
    fade_effect: true
    location:
      world: spawn
      x: -54.5
      y: 79.62000000476837
      z: -41.5
      yaw: 0.93607324
      pitch: -7.65004
  mannequin:
    location:
      world: spawn
      x: -54.5
      y: 78.0625
      z: -38.5
      yaw: 179.13638
      pitch: 4.799979
  teleport_area:
    enter:
      world: flat
      pos1:
        x: 167
        y: -61
        z: 42
      pos2:
        x: 167
        y: -57
        z: 37
    exit_location:
      world: spawn
      x: -36.33065831093231
      y: 62.9375
      z: -43.64031086411282
      yaw: -68.06349
      pitch: -7.34998
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
      add_item_in_blank_slots:
        # This is useful only for some expert users that need to do some crazy stuff.
        # Do not enable it if you don't know what you are doing.
        enabled: false
        type: PAPER
        custom_model_data: 1337666
send_creative_hidden_hat_message: true
save:
  # Use only one at a time
  file:
    enabled: true
  mysql:
    enabled: false
    url: jdbc:mysql://my_url_database_69.com:3306/database_name
    username: username
    password: password
    table: cosmeticscore_saved
debug: false
```

### Problematic items yml configuration file (optional)

```shell
cosmetics:
  bs_balloon_bee:
    enabled: true
    display_name: "Bee Balloon"
    type: MEG_BALLOON_ENTITY
    model:
      gui: paper:26
      normal: bs_balloon_bee
    dye:
      enabled: true
      default: "#ffffff"
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://i.gyazo.com/thumb/1200/ff02c86ad90400f6bcff4750f908dd20-jpg.jpg

**Comment by leestar960** [comment]
hey?

**Comment by LoneDev6** [comment]
Will be checked in the next days, thanks for the patience.

**Comment by LoneDev6** [comment]
I cannot reproduce the issue.

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/27242001/4de90800-fe12-4de3-abaf-cb50342e11e8)
![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/27242001/9e2e2b25-ee8b-4ae3-a0ef-433c26f31017)

```yml
cosmetics:

  # Example custom balloon created with ModelEngine entities (supports also animated ModelEngine entities models)
  meg_amogus_balloon:
    enabled: true
    display_name: "Amogus Balloon (MEG)"
    type: MEG_BALLOON_ENTITY
    # Showing a different item into the GUI (in this case it's a must because ModelEngine entities can't be put in GUIs)
    model:
      gui: potion:400014
      normal: amogus
    dye:
      enabled: true
      default: "#ffffff"
```
