### ISSUE TITLE
Cosmetics Core Lore Placeholders

### ISSUE THREAD

**Issue by emcrald** [PluginBugs/Issues-CosmeticsCore#222]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

emcrald

### Describe the solution you'd like

The ability to use any placeholder api placeholders inside the lore and even the name of the cosmetic.

The story:
I have a shop I made using deluxe menus to buy cosmetics and I've been using the changeoutput placeholder api package to determine inside the cosmetics lore either if the user owns the item to display "Owned" or whether to display "Purchase + The Price". This would be very useful inside the cosmetics core gui to show if the item is owned or not in my case, but there would be countless other cases where people can be very creative with what they do with it.

Heres an example of my messy placeholder but there are other placeholders that offer more cleaner and easier to understand methods: 
`'%changeoutput_==_input:{luckperms_has_permission_cosmeticscore.user.cosmetics.wear.carrot_hat}_matcher:yes_ifmatch:&r&f셁_else:&r&f셂\n&r&f셃셋ꌄ₁₀₀%'`

Output:
![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/69999498/de4657a1-1679-4c85-96cc-9d7923de10c0)
![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/69999498/6d6e41ea-ab30-495e-a294-2c914bfb47e5)

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

None

**Comment by LoneDev6** [comment]
Will be possible in the next update.
Done:
```yml
  leather_backpack:
    enabled: true
    display_name: "Leather Backpack"
    type: BODY_ITEM
    model:
      gui: potion:300001
      normal: potion:300001
      normal_2: potion:310001
      self: potion:300002
      self_2: potion:310002
    dye:
      enabled: true
      default: "#542900"
    lore:
    - test %player_name%
```

NOTE: this will break any json (component) you are using in your lore. This will work only on legacy simple strings due to the fact that PlaceholderAPI doesn't support components replacement.
