### ISSUE TITLE
Compatibility Issues with mythic mob's mouttarget skills.

### ISSUE THREAD

**Issue by Ecilpse** [PluginBugs/Issues-CosmeticsCore#237]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

Eclipse

### What happened?

when player cast skil's with mouttarget, bag cosmetics was unequipped.

### Steps to reproduce the issue

just equip bag cosmetics and cast below skill. (/mm test cast test_equip)

skills
```

test:
  Skills:
  - summon{type=test_equip;amount=1;radius=0;yRadius=0;onSurface=true} @forward{f=7;y=0}
  
```

mobs
```
test_equip:
  Type: ARMOR_STAND
  Faction: vfx
  Pose:
      RightArm: 0,0,0
  ItemHand: dragon_dash_charge_1
  Options:
    despawn: true
    Marker: false
    Interactable: false
    Small: false
    HasArms: true
    Invisible: true
    Invincible: true
  Skills:
  - mounttarget @Owner ~onSpawn
```

### Server version

1.20.1 purpur

### CosmeticsCore Version

1.3.0-release-1

### ProtocolLib Version

5.1.1

### LoneLibs Version

1.0.54

### Screenshots/Videos (you can drag and drop files or paste links)

https://github.com/PluginBugs/Issues-CosmeticsCore/assets/25452835/81beb448-5277-4c49-9e2e-6d6bf895b6e3
