### ISSUE TITLE
Option to remove cursor from wardrobe and make player rotate automatically

### ISSUE THREAD

**Issue by xn80a32** [PluginBugs/Issues-CosmeticsCore#240]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Add an option to remove cursor from wardrobe (cause it often laggy and have an annoying delay) and make player rotate automatically, like in other cosmetics plugins. With that option plugin will be way more better

### Is your feature request related to a problem?

> nah

> 

> ****

### Describe alternatives you've considered

idk man

**Comment by SrMonsterYT** [comment]
great suggestion, I also think it should rotate automatically, and there should be hand cosmetics too

**Comment by SrMonsterYT** [comment]
it's a good option, leave it as an option in the settings, I prefer it rotating too

**Comment by LoneDev6** [comment]
New options are going to be implemented:
```yml
wardrobe_room:
  camera:
    show_cursor: true # Show or hide the cursor
    rotation:
      enabled: true
      auto_rotate: # automatic rotation
        enabled: false
        direction: RIGHT # direction of the npc rotation
        step: 5 # rotation amount each 1 tick
```
