### ISSUE TITLE
Add the ability to add tooltip_style in cosmetic

### ISSUE THREAD

**Issue by sadcreativ** [PluginBugs/Issues-CosmeticsCore#308]
### Terms

- [x] I'm using the very latest version of CosmeticsCore and its dependencies.
- [x] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same suggestion was already reported.
- [x] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if the feature is already implemented.
- [x] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

sad_creativ

### Describe the solution you'd like

I have a suggestion to add the ability to add tooltip_style a new minecraft feature for cosmetics. It's a great feature and I don't understand why plugins ignore it.

How the item looks in GUI
![Image](https://github.com/user-attachments/assets/653eb7b8-43ab-4eb8-aa0b-f6252b44eaeb)

What it might look like in GUI with my custom tooltip_style:
![Image](https://github.com/user-attachments/assets/342bcf19-49b7-45df-8527-d31f8067af2c)

![Image](https://github.com/user-attachments/assets/20a98a1e-7212-48e2-90eb-76586a6f979f)

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

I have no idea how to do this.

### Additional context

I also didn't find if it's possible to make lore for cosmetics, like add a description or where to get it

**Comment by LoneDev6** [comment]
Implemented in the upcoming update

![Image](https://github.com/user-attachments/assets/ffae223e-b69b-4d84-b442-1aac1c0eb721)

```yml
cosmetics:
  balloon_diamond_block:
    enabled: true
    display_name: "Diamond Block"
    tooltip_style: rainbow
    type: BALLOON
    model:
      gui: DIAMOND_BLOCK
      normal: DIAMOND_BLOCK
```
