### ISSUE TITLE
Dye not applying on the new BALLOON_ITEM type cosmetic

### ISSUE THREAD

**Issue by Braynblocks** [PluginBugs/Issues-CosmeticsCore#318]
### Terms

- [x] I'm using the very latest version of CosmeticsCore and its dependencies.
- [x] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [x] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [x] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

As title said, inside the wardrobe, the color gets applied correctly on BALLOON_ITEM however as soon as you select the cosmetic and get out of the wardrobe, the dye will not apply, and it will go back to the default color.

### Steps to reproduce the issue

1. Enter wardrobe.
2. Go to balloon section of the GUI and select a dyeable BALLOON_ITEM.
3. Choose color and select the balloon cosmetic.
4. Leave the wardrobe.

- The balloon cosmetic will not have any dye applied to it.

### CosmeticsCore Version

CosmeticsCore Version: 1.3.5

### ProtocolLib Version

ProtocolLib Version: 5.4.0

### Error (optional)

```shell

```

### CosmeticsCore config.yml

```shell

```

### Problematic items yml configuration file (optional)

```shell

```

**Comment by LoneDev6** [comment]
Can you provide an example configuration of that?
Are you trying to manually create a potion with custom model?

**Comment by Braynblocks** [comment]
> Can you provide an example configuration of that? Are you trying to manually create a potion with custom model?

I added an item pack I got via ItemsAdder and these items' IDs are LEATHER_HORSE_ARMOR (they are dyeable). So what I did is get their custom_model_data in game and add them to CosmeticsCore like this:

```yml
balloontest1:
    enabled: true
    display_name: "Balloon Test 1"
    type: BALLOON
    balloon:
      leash: false
    model:
      gui: LEATHER_HORSE_ARMOR:10172
      normal: LEATHER_HORSE_ARMOR:10172
    dye:
      enabled: true
```
