### ISSUE TITLE
Add new balloon type:BALLOON_ITEM

### ISSUE THREAD

**Issue by minecraft-dripdrop** [PluginBugs/Issues-CosmeticsCore#32]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

make itemsadder entity is pretty hard to me.
is it possible just make a model to be a balloon?Just use PAPER and CustomModelData
Here is the plugin can do it,may be helpful for you .
https://www.spigotmc.org/resources/balloons.101083/

### Is your feature request related to a problem?

no

### Describe alternatives you've considered

make balloon easier

**Comment by LoneDev6** [comment]
Implemented in the upcoming version.
Can be downloaded on Discord beta channel.
```yml
cosmetics:
  simple_diamond_block_balloon:
    enabled: true
    display_name: "Simple Diamond Block Balloon"
    type: BALLOON
    model:
      gui: DIAMOND_BLOCK
      normal: DIAMOND_BLOCK
    dye:
      enabled: true
      default: "#ff0000"
  simple_itemsadder_item_balloon:
    enabled: true
    display_name: "Simple ItemsAdder Item Balloon"
    type: BALLOON
    model:
      gui: iasurvival:ruby
      normal: iasurvival:ruby
    dye:
      enabled: true
      default: "#ff0000"
```
