### ISSUE TITLE
Option to disable the leash on cosmetics.

### ISSUE THREAD

**Issue by taleno503** [PluginBugs/Issues-CosmeticsCore#47]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

taleno503

### Describe the solution you'd like

there are some cosmetic which doesn't need leash for example, drone, ghost!
More over i would like to add suggest this feature.

- lores for each cosmetic.
- Make the lores and titles  support the itemsAdder placeolder custon Font in each cosmetics, in order to add differents custon font, for example icons, colorable o no colorable icons...

### Is your feature request related to a problem?

there is not problem 

### Describe alternatives you've considered

That's all!!

**Comment by LoneDev6** [comment]
> Option to disable the leash on cosmetics.

Will be implemented in the upcoming update:
```yml
cosmetics:
  
  # Example custom balloon created with ItemsAdder entities (supports also animated ItemsAdder entities models)
  amogus_balloon:
    enabled: true
    display_name: "Amogus Balloon"
    type: BALLOON_ENTITY
    # Showing a different item into the GUI (in this case it's a must because ItemsAdder entities can't be put in GUIs)
    model:
      gui: potion:400014
      normal: cosmetics:amogus
    dye:
      enabled: true
      default: "#ff0000"
    lore:
      - "line1"
      - "line2"
    balloon:
      leash: false
```


> lores for each cosmetic.

Already implemented, use the `lore` property

```yml
cosmetics:
  
  # Example custom balloon created with ItemsAdder entities (supports also animated ItemsAdder entities models)
  amogus_balloon:
    enabled: true
    display_name: "Amogus Balloon"
    type: BALLOON_ENTITY
    # Showing a different item into the GUI (in this case it's a must because ItemsAdder entities can't be put in GUIs)
    model:
      gui: potion:400014
      normal: cosmetics:amogus
    dye:
      enabled: true
      default: "#ff0000"
    lore:
      - "line1"
      - "line2"
```

> Make the lores and titles support the itemsAdder placeolder

Already implemented
